# Generated by Django 4.2 on 2023-06-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='todo',
            field=models.TextField(null=True),
        ),
    ]
