# Generated by Django 4.2 on 2023-06-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_works_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
